import { PageHeader, SectionHeading, StatusBadge } from "../_components/PagePrimitives";

const plans = [
  {name:"Starter",price:"USD 49",description:"Para una operación pequeña con un número, CRM y usuarios básicos.",features:["1 empresa","1 número WhatsApp","3 usuarios","CRM y conversaciones","Soporte estándar"]},
  {name:"Professional",price:"USD 99",description:"Para equipos comerciales con automatización, campañas y métricas avanzadas.",features:["1 empresa","1 número WhatsApp","10 usuarios","Campañas y recovery","Analytics avanzado"]},
  {name:"Scale",price:"A medida",description:"Para múltiples unidades, mayor volumen y soporte prioritario.",features:["Multiempresa","Varios números","Usuarios ampliados","SLA y auditoría","Integraciones personalizadas"]},
];

export default function PlansPage(){return <><PageHeader kicker="PLANES" title="Catálogo comercial" description="Presentación profesional de los niveles de servicio, límites y capacidades previstas para la versión SaaS."/><section className="saas-section" style={{marginTop:0}}><SectionHeading title="Planes disponibles" description="Estructura visual preparada para edición, comparación y asignación por empresa."/><div className="saas-grid">{plans.map((plan,index)=><article className="saas-card" key={plan.name}><div className="saas-card-top"><h3>{plan.name}</h3><StatusBadge tone={index===1?"success":"neutral"}>{index===1?"Recomendado":"Disponible"}</StatusBadge></div><strong style={{display:"block",fontSize:"2rem",margin:"16px 0 8px",letterSpacing:"-.04em"}}>{plan.price}</strong><p>{plan.description}</p><div className="saas-list">{plan.features.map(feature=><div className="saas-list-row" key={feature}><span>Incluye</span><strong>{feature}</strong></div>)}</div><div className="saas-card-actions"><button className={`saas-button ${index===1?"primary":""}`} type="button">Configurar plan</button></div></article>)}</div></section><section className="saas-section"><SectionHeading title="Reglas y límites" description="Parámetros que la versión final controlará por cada suscripción."/><div className="saas-grid"><article className="saas-card"><h3>Usuarios</h3><p>Límites por plan, invitaciones, roles y bloqueo automático al superar la capacidad.</p></article><article className="saas-card"><h3>Mensajería</h3><p>Volumen mensual, consumo, alertas y costos adicionales por uso.</p></article><article className="saas-card"><h3>Módulos</h3><p>CRM, campañas, analytics, recovery, integraciones y auditoría según el plan.</p></article></div></section></>}
